name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tf
    steps:
      - uses: actions/checkout@v1

  terraform:
    name: Setup Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tf
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - id: init
        run: terraform init

      - id: plan
        run: terraform plan -no-color

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
