name: Deploy Production

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./

jobs:
  tf_fmt:
    name: Setup Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - id: init
        run: terraform init

      - id: plan
        run: terraform plan -no-color

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
